version: 2
updates:
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: "/backend"
    schedule:
      interval: monthly
