version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://testuser:testpassword@db:5432/testdb
    command: ["pipenv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - .env.backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env.frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
    db-data:
