name: Test Docker Image Build

on:
  pull_request:
    paths-ignore:
      - 'README.md'
    branches:
      - main


jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: |
      (
        github.actor == 'dependabot[bot]' ||
        github.actor == 'dependabot'
      )
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.function }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        service: [frontend, backend]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: false
          tags: book-search/${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
